-- --------------------------------------------------------
-- 호스트:                          221.168.38.108
-- 서버 버전:                        10.6.5-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- monitoring 데이터베이스 구조 내보내기
CREATE DATABASE IF NOT EXISTS `monitoring` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `monitoring`;

-- 테이블 monitoring.MEMBER 구조 내보내기
CREATE TABLE IF NOT EXISTS `MEMBER` (
  `MEMBER_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '번호',
  `MEMBER_ID` varchar(50) DEFAULT NULL COMMENT '아이디',
  `MEMBER_PWD` varchar(255) DEFAULT NULL COMMENT '비밀번호',
  `MEMBER_ROLE` varchar(50) DEFAULT NULL COMMENT '권한',
  `MEMBER_MOD_DATE` varchar(50) DEFAULT NULL COMMENT '수정날짜',
  PRIMARY KEY (`MEMBER_NO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='회원정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 monitoring.SERVER 구조 내보내기
CREATE TABLE IF NOT EXISTS `SERVER` (
  `SERVER_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '서버번호(PK)',
  `SERVER_NAME` varchar(100) DEFAULT NULL COMMENT '서버명',
  `SERVER_COMPANY` varchar(50) DEFAULT NULL COMMENT '서버위치',
  `SERVER_PUBLICIP` varchar(100) DEFAULT NULL COMMENT '공인아이피',
  `SERVER_PRIVATEIP` varchar(100) DEFAULT NULL COMMENT '내부아이피',
  `SERVER_GUBUN` varchar(100) DEFAULT NULL COMMENT '구분',
  `SERVER_CPU` varchar(50) DEFAULT NULL COMMENT 'CPU정보',
  `SERVER_OS` varchar(50) DEFAULT NULL COMMENT '운영체제',
  `SERVER_MEMORY` varchar(100) DEFAULT NULL COMMENT '메모리',
  `SERVER_COST` varchar(50) DEFAULT NULL COMMENT '비용',
  `SERVER_ETC` varchar(255) DEFAULT NULL COMMENT '메모',
  PRIMARY KEY (`SERVER_NO`),
  KEY `SERVER_NAME` (`SERVER_NAME`),
  KEY `SERVER_PUBLICIP` (`SERVER_PUBLICIP`),
  KEY `SERVER_PRIVATEIP` (`SERVER_PRIVATEIP`),
  KEY `SERVER_COMPANY` (`SERVER_COMPANY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 monitoring.SERVER_DISK 구조 내보내기
CREATE TABLE IF NOT EXISTS `SERVER_DISK` (
  `SERVER_DISK_NO` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '디스크번호(PK)',
  `SERVER_DISK_CAPACITY` varchar(50) NOT NULL DEFAULT '0' COMMENT '디스크용량',
  `SERVER_DISK_NAME` varchar(50) DEFAULT NULL COMMENT '디스크구분',
  `SERVER_NO` int(11) NOT NULL COMMENT '서버번호(외래키)',
  PRIMARY KEY (`SERVER_DISK_NO`),
  KEY `FK_server_disk_server` (`SERVER_NO`),
  CONSTRAINT `FK_server_disk_server` FOREIGN KEY (`SERVER_NO`) REFERENCES `SERVER` (`SERVER_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서버별 하드디스크 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 monitoring.SERVER_DISK_STATUS 구조 내보내기
CREATE TABLE IF NOT EXISTS `SERVER_DISK_STATUS` (
  `SERVER_DISK_STATUS_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '디스크상태번호(PK)',
  `SERVER_DISK_NO` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '디스크번호',
  `SERVER_NO` int(11) DEFAULT NULL COMMENT '서버번호',
  `SERVER_STATUS_NO` varchar(50) DEFAULT NULL COMMENT '서버상태번호',
  `SERVER_DISK_STATUS_PERCENTAGE` varchar(50) DEFAULT NULL COMMENT '디스크사용량',
  `SERVER_DISK_STATUS_TIME` timestamp NULL DEFAULT current_timestamp() COMMENT '상태기록날짜',
  PRIMARY KEY (`SERVER_DISK_STATUS_NO`),
  KEY `FK_SERVER_DISK_STATUS_SERVER_DISK` (`SERVER_DISK_NO`),
  KEY `FK_SERVER_DISK_STATUS_SERVER` (`SERVER_NO`),
  KEY `FK_SERVER_DISK_STATUS_SERVER_STATUS` (`SERVER_STATUS_NO`),
  CONSTRAINT `FK_SERVER_DISK_STATUS_SERVER` FOREIGN KEY (`SERVER_NO`) REFERENCES `SERVER` (`SERVER_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_SERVER_DISK_STATUS_SERVER_DISK` FOREIGN KEY (`SERVER_DISK_NO`) REFERENCES `SERVER_DISK` (`SERVER_DISK_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_SERVER_DISK_STATUS_SERVER_STATUS` FOREIGN KEY (`SERVER_STATUS_NO`) REFERENCES `SERVER_STATUS` (`SERVER_STATUS_UUID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 monitoring.SERVER_LINUX_USERINFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `SERVER_LINUX_USERINFO` (
  `SERVER_NO` int(11) DEFAULT NULL COMMENT '서버번호(FK)',
  `SERVER_USERNAME` varchar(255) DEFAULT NULL COMMENT '리눅스 접속 아이디',
  `SERVER_USERPWD` varchar(255) DEFAULT NULL COMMENT '리눅스 접속 비밀번호',
  `SERVER_SSHPORT` int(20) DEFAULT 22 COMMENT 'SSH 연결 포트번호',
  KEY `FK_SERVER_LINUX_USERINFO_SERVER` (`SERVER_NO`),
  CONSTRAINT `FK_SERVER_LINUX_USERINFO_SERVER` FOREIGN KEY (`SERVER_NO`) REFERENCES `SERVER` (`SERVER_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='리눅스 접속정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 monitoring.SERVER_STATUS 구조 내보내기
CREATE TABLE IF NOT EXISTS `SERVER_STATUS` (
  `SERVER_STATUS_UUID` varchar(255) NOT NULL COMMENT '서버상태번호(PK/UUID)',
  `SERVER_NO` int(11) DEFAULT NULL COMMENT '서버번호',
  `SERVER_STATUS_CPU_PERCENTAGE` varchar(50) DEFAULT NULL COMMENT '서버CPU사용량',
  `SERVER_STATUS_MEMORY_PERCENTAGE` varchar(50) DEFAULT NULL COMMENT '서버메모리사용량',
  `SERVER_STATUS_TIME` timestamp NULL DEFAULT current_timestamp() COMMENT '상태기록날짜',
  PRIMARY KEY (`SERVER_STATUS_UUID`) USING BTREE,
  KEY `FK_SERVER_STATUS_SERVER` (`SERVER_NO`),
  CONSTRAINT `FK_SERVER_STATUS_SERVER` FOREIGN KEY (`SERVER_NO`) REFERENCES `SERVER` (`SERVER_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서버 상태';

-- 내보낼 데이터가 선택되어 있지 않습니다.

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
